svg_icons:
  default: "circle-play|forward-step|arrow-up-right-from-square|window-restore"
  type: list
  list_type: "compact"
  description: "List of FontAwesome 6 icons used in this theme component"
